### ISSUE TITLE
name confusion : test / testsuite

### ISSUE THREAD

**Issue by mixmix** [AljoschaMeyer/shs1-test#3]
I was trying to install this today and ran:

```bash
$ npm install shs1-testsuite --save-dev
```

because that's the name of the repo right? turns out the _package.name_ is `shs1-test` though!

I recommend bringing these into alignment:
- EITHER : rename `shs1-test` everywhere  << this one is easier to type! 
- OR : rename `shs1-testsuire` everywhere  << (edit, see, I made a typo:)

**Comment by mixmix** [comment]
OH ... note that any rename would be good to rename / alias the bin commands files to be consistent too

**Comment by mixmix** [comment]
oh I just tripped on the bin command too `shs1testclient` has a different pattern with no kebab-case ):

**Comment by AljoschaMeyer** [comment]
Renamed the repo to `shs1-test`. There should be no other places that need to be changed, right?

I don't think I want to rename the bin commands. Technically that would be a breaking change, and I prefer to reserve `-` for options (even though *technically* it's unambiguous).

**Comment by mixmix** [comment]
github is smart so people who've linked here will get redirected to the new location.

yeah nice notice on - for flags .... the command line bin thing I think you could have multiple bin commands which point to the same file, but yeah I think this is sufficient
